config/routes.rb
LaptopCheckout::Application.routes.draw do
  resources :user_histories, :path => "user/history"
  resources :laptop_histories, :path => "laptop/history"
  resources :transactions
  resources :users, :path => "manage/users"
  resources :laptops, :path => "manage/laptops"
  
  match 'check-in' => 'laptops#scan', via: [:get, :post]
  get 'check-out' => 'transactions#new'
  get 'status' => 'transactions#index'
  get 'manage' => 'index#manage'
  get 'history' => 'transactions#index_all'

  resources :laptops do
    put :scan, :on => :collection
  end
 
  get 'user/view' => 'user_histories#search'
  resources :user_histories do
    collection do
      get 'search'
    end
  end
  
  get 'laptop/view' => 'laptop_histories#search'
  resources :laptop_histories do
    collection do
      get 'search'
    end
  end
  

    

  root 'index#home'

end

app/models/user_history.rb
class UserHistory < ActiveRecord::Base
end

app/controllers/user_histories_controller.rb
class UserHistoriesController < ApplicationController
  before_action :set_user_history, only: [:show, :edit, :update, :destroy, :create]
  
  #<%= link_to k.name, :controller => "search", :action => "keywords", :search => k.name %>
  def search
    @user_histories = UserHistory.where(:user_id => params[:user_id])
    render :action => :index
  end
  
  # GET /user_histories
  # GET /user_histories.json
  def index
    @user_histories = UserHistory.all
  end

  # GET /user_histories/1
  # GET /user_histories/1.json
  def show
  end

  # GET /user_histories/new
  def new
    @user_history = UserHistory.new
  end

  # GET /user_histories/1/edit
  def edit
  end

  # POST /user_histories
  # POST /user_histories.json
  def create
    @user_history = UserHistory.new(user_history_params)

    respond_to do |format|
      if @user_history.save
        format.html { redirect_to @user_history, notice: 'User history was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user_history }
      else
        format.html { render action: 'new' }
        format.json { render json: @user_history.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def add_record(transaction)
    record = UserHistory.new(:user_id => transaction.users_id, :transaction_id => transaction.id)
    record.save
  end

  # PATCH/PUT /user_histories/1
  # PATCH/PUT /user_histories/1.json
  def update
    respond_to do |format|
      if @user_history.update(user_history_params)
        format.html { redirect_to @user_history, notice: 'User history was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_histories/1
  # DELETE /user_histories/1.json
  def destroy
    @user_history.destroy
    respond_to do |format|
      format.html { redirect_to user_histories_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_history
      @user_history = UserHistory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_history_params
      params.require(:user_history).permit(:user_id, :transaction_id)
    end
end

app/helpers/user_histories_helper.rb
module UserHistoriesHelper
end

app/views/user_histories/_form.html.erb
<%= form_for(@user_history) do |f| %>
  <% if @user_history.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_history.errors.count, "error") %> prohibited this user_history from being saved:</h2>

      <ul>
      <% @user_history.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :transaction_id %><br>
    <%= f.number_field :transaction_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_histories/edit.html.erb
<h1>Editing user_history</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_history %> |
<%= link_to 'Back', user_histories_path %>

app/views/user_histories/index.html.erb
<% provide(:title, 'History') %>
<style>		
		h1 {
			text-align: center;
			font-family: arial;
			font-size: 20px;
		}
		
		table {
			border-collapse: collapse;
			width: 0 auto;
			margin: 0 auto;
			empty-cells: show;	
		}
		
		table tr th {
			border-bottom: 2px solid black;
		}
		
		table tr {
			text-align: left;
		}
		

		td, th {
			padding-right: 10px;
			padding-left: 10px;
			width: 0 auto;
		}	
		
		#navbar {
			width: 0 auto;
			margin: 0 auto;
			float: left;
		}
		#navbar2 {
			width: 0 auto;
			margin: 0 auto;
			float: right;
		}
		
		#spacing {
			padding-right: 40px;
		}
		
		#id {
			text-align: center;
		}
		
		#bottom_border {
			border-top: 2px solid black;
			padding-top: 5px;
		}
		a { color: #000; }
		a:visited { color: #000; }
		a:hover { color: #fff; background-color:#000; }
</style>
<br />
<header id="logo"></header>

<h1>User History</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Laptop</th>
      <th>Checked Out</th>
      <th>Checked In</th>
    </tr>
  </thead>

  <tbody>
    <% @user_histories.each do |user_history| %>
      <tr>
      	<td id="name_td2"><%= UsersController.new.find_user_by_id(user_history.user_id.to_i) %> </td>
    	<td>
	    	<%= link_to TransactionsController.new.history_report(user_history.transaction_id.to_i, 0),
	    		:controller => "laptop_histories",
	    		:action => "search",
	    		:laptop_id => TransactionsController.new.history_report(user_history.transaction_id.to_i, 4) %>
    	</td>
        <td id="time_td"><%= TransactionsController.new.history_report(user_history.transaction_id.to_i, 1) %></td>
        <td id="time_td"><%= TransactionsController.new.history_report(user_history.transaction_id.to_i, 2) %></td>
      </tr>
    <% end %>
  </tbody>
  
  <tr>
  	<td id="bottom_border">
  		<div id="navbar">
			<a href="/status"><button id="small_button">Back</button></a>
		</div>
  	</td>
  	<td id="bottom_border"></td>
  	<td id="bottom_border"></td>
  	<td id="bottom_border">
  		<div id="navbar2">
			<a href=<%= root_path %>><button id="small_button">Home</button></a>
		</div>
  	</td>
  </tr>
  
</table>
<br>

app/views/user_histories/new.html.erb
<h1>New user_history</h1>

<%= render 'form' %>

<%= link_to 'Back', user_histories_path %>

app/views/user_histories/search.html.erb
<%= form_tag(search_user_histories_path, :method => "get") do %>
  <div>
    <%= label_tag(:user, "User ID:") %>
    <%= text_field_tag(:user_id, params[:user_id]) %>
  </div>
  
  <div>
    <%= submit_tag("Search") %>
  </div>
<% end %>

app/views/user_histories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user_history.user_id %>
</p>

<p>
  <strong>Transaction:</strong>
  <%= @user_history.transaction_id %>
</p>

<%= link_to 'Edit', edit_user_history_path(@user_history) %> |
<%= link_to 'Back', user_histories_path %>