config/routes.rb
LaptopCheckout::Application.routes.draw do
  resources :user_histories, :path => "user/history"
  resources :laptop_histories, :path => "laptop/history"
  resources :transactions
  resources :users, :path => "manage/users"
  resources :laptops, :path => "manage/laptops"
  
  match 'check-in' => 'laptops#scan', via: [:get, :post]
  get 'check-out' => 'transactions#new'
  get 'status' => 'transactions#index'
  get 'manage' => 'index#manage'
  get 'history' => 'transactions#index_all'

  resources :laptops do
    put :scan, :on => :collection
  end
 
  get 'user/view' => 'user_histories#search'
  resources :user_histories do
    collection do
      get 'search'
    end
  end
  
  get 'laptop/view' => 'laptop_histories#search'
  resources :laptop_histories do
    collection do
      get 'search'
    end
  end
  

    

  root 'index#home'

end

app/models/laptop_history.rb
class LaptopHistory < ActiveRecord::Base
end

app/controllers/laptop_histories_controller.rb
class LaptopHistoriesController < ApplicationController
  before_action :set_laptop_history, only: [:show, :edit, :update, :destroy, :create]

  # GET /laptop_histories
  # GET /laptop_histories.json
  def search
    @laptop_histories = LaptopHistory.where(:laptop_id => params[:laptop_id])
    render :action => :index
  end
  
  def index
    @laptop_histories = LaptopHistory.all
  end

  # GET /laptop_histories/1
  # GET /laptop_histories/1.json
  def show
  end

  # GET /laptop_histories/new
  def new
    @laptop_history = LaptopHistory.new
  end

  # GET /laptop_histories/1/edit
  def edit
  end

  # POST /laptop_histories
  # POST /laptop_histories.json
  def create
    @laptop_history = LaptopHistory.new(laptop_history_params)

    respond_to do |format|
      if @laptop_history.save
        format.html { redirect_to @laptop_history, notice: 'Laptop history was successfully created.' }
        format.json { render action: 'show', status: :created, location: @laptop_history }
      else
        format.html { render action: 'new' }
        format.json { render json: @laptop_history.errors, status: :unprocessable_entity }
      end
    end
  end

  def add_record(transaction)
    record = LaptopHistory.new(:laptop_id => transaction.laptops_id, :transaction_id => transaction.id)
    record.save
  end

  # PATCH/PUT /laptop_histories/1
  # PATCH/PUT /laptop_histories/1.json
  def update
    respond_to do |format|
      if @laptop_history.update(laptop_history_params)
        format.html { redirect_to @laptop_history, notice: 'Laptop history was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @laptop_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /laptop_histories/1
  # DELETE /laptop_histories/1.json
  def destroy
    @laptop_history.destroy
    respond_to do |format|
      format.html { redirect_to laptop_histories_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_laptop_history
      @laptop_history = LaptopHistory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def laptop_history_params
      params.require(:laptop_history).permit(:laptop_id, :transaction_id)
    end
end

app/helpers/laptop_histories_helper.rb
module LaptopHistoriesHelper
end

app/views/laptop_histories/_form.html.erb
<%= form_for(@laptop_history) do |f| %>
  <% if @laptop_history.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@laptop_history.errors.count, "error") %> prohibited this laptop_history from being saved:</h2>

      <ul>
      <% @laptop_history.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :laptop_id %><br>
    <%= f.number_field :laptop_id %>
  </div>
  <div class="field">
    <%= f.label :transaction_id %><br>
    <%= f.number_field :transaction_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/laptop_histories/edit.html.erb
<h1>Editing laptop_history</h1>

<%= render 'form' %>

<%= link_to 'Show', @laptop_history %> |
<%= link_to 'Back', laptop_histories_path %>

app/views/laptop_histories/index.html.erb
<% provide(:title, 'History') %>
<style>		
		h1 {
			text-align: center;
			font-family: arial;
			font-size: 20px;
		}
		
		table {
			border-collapse: collapse;
			width: 0 auto;
			margin: 0 auto;
			empty-cells: show;	
		}
		
		table tr th {
			border-bottom: 2px solid black;
		}
		
		table tr {
			text-align: left;
		}
		
		td, th {
			padding-right: 10px;
			padding-left: 10px;
			width: 0 auto;
		}	
		
		#navbar {
			width: 0 auto;
			margin: 0 auto;
			float: left;
		}
		#navbar2 {
			width: 0 auto;
			margin: 0 auto;
			float: right;
		}
		
		#spacing {
			padding-right: 20px;
			padding-left: 20px;
		}
		
		#id {
			text-align: center;
		}
		
		#bottom_border {
			border-top: 2px solid black;
			padding-top: 5px;
		}
		a { color: #000; }
		a:visited { color: #000; }
		a:hover { color: #fff; background-color:#000; }
</style>
<br />
<header id="logo"></header>

<h1>Laptop History</h1>

<table>
  <thead>
    <tr>
      <th>Laptop</th>
      <th>User</th>
      <th>Checked Out</th>
      <th>Checked In</th>
    </tr>
  </thead>

  <tbody>
    <% @laptop_histories.each do |laptop_history| %>
      <tr>
      	<td id="name_td2"><%= LaptopsController.new.find_laptop_by_id(laptop_history.laptop_id.to_i) %> </td>
    	<td>
	    	<%= link_to TransactionsController.new.history_report(laptop_history.transaction_id.to_i, 3),
	    		:controller => "user_histories",
	    		:action => "search",
	    		:user_id => TransactionsController.new.history_report(laptop_history.transaction_id.to_i, 5) %>
    	</td>
        <td id="time_td"><%= TransactionsController.new.history_report(laptop_history.transaction_id.to_i, 1) %></td>
        <td id="time_td"><%= TransactionsController.new.history_report(laptop_history.transaction_id.to_i, 2) %></td>
      </tr>
    <% end %>
  </tbody>
  
  <tr>
  	<td id="bottom_border">
  		<div id="navbar">
			<a href="/status"><button id="small_button">Back</button></a>
		</div>
  	</td>
  	<td id="bottom_border"></td>
  	<td id="bottom_border"></td>
  	<td id="bottom_border">
  		<div id="navbar2">
			<a href=<%= root_path %>><button id="small_button">Home</button></a>
		</div>
  	</td>
  </tr>
  
</table>
<br>

app/views/laptop_histories/new.html.erb
<h1>New laptop_history</h1>

<%= render 'form' %>

<%= link_to 'Back', laptop_histories_path %>

app/views/laptop_histories/search.html.erb
<%= form_tag(search_laptop_histories_path, :method => "get") do %>
  <div>
    <%= label_tag(:laptop, "Laptop ID:") %>
    <%= text_field_tag(:laptop_id, params[:laptop_id]) %>
  </div>
  
  <div>
    <%= submit_tag("Search") %>
  </div>
<% end %>

app/views/laptop_histories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Laptop:</strong>
  <%= @laptop_history.laptop_id %>
</p>

<p>
  <strong>Transaction:</strong>
  <%= @laptop_history.transaction_id %>
</p>

<%= link_to 'Edit', edit_laptop_history_path(@laptop_history) %> |
<%= link_to 'Back', laptop_histories_path %>