config/routes.rb
LaptopCheckout::Application.routes.draw do
  resources :user_histories, :path => "user/history"
  resources :laptop_histories, :path => "laptop/history"
  resources :transactions
  resources :users, :path => "manage/users"
  resources :laptops, :path => "manage/laptops"
  
  match 'check-in' => 'laptops#scan', via: [:get, :post]
  get 'check-out' => 'transactions#new'
  get 'status' => 'transactions#index'
  get 'manage' => 'index#manage'
  get 'history' => 'transactions#index_all'

  resources :laptops do
    put :scan, :on => :collection
  end
 
  get 'user/view' => 'user_histories#search'
  resources :user_histories do
    collection do
      get 'search'
    end
  end
  
  get 'laptop/view' => 'laptop_histories#search'
  resources :laptop_histories do
    collection do
      get 'search'
    end
  end
  

    

  root 'index#home'

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]
  #after_filter :check_out, only: [:create]
  
  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = Transaction.all
  end
  
  def index_all
    @transactions = Transaction.all
  end
  
  def check_if_laptop_is_available(id)
    transactions = Transaction.all
    transactions.each do |x|
      if x.laptops_id != id then
        return true
      end
    end
  end
  
  def check_out
    @transaction.update_attribute(:checked_out, true)
    @transaction.update_attribute(:checked_out_time,  Time.zone.now)
    match_id = @transaction.laptops_id
    laptops = Laptop.all
    
    laptops.each do |x|
      if x.id == match_id then
        x.update_attribute(:available, false)
      end
    end
  end
  
  def check_in
    @transaction.update_attribute(:checked_out, false)
    @transaction.update_attribute(:checked_in_time,  Time.zone.now)
  end
  
  def format_timestamp(timestamp)
    if timestamp == nil then
      return "N/A"
    else
      date = timestamp.strftime "%Y/%m/%d"
      time = timestamp.strftime "%l:%M:%S%p"
      time_split = time.split ":"
  
      time_split[0] = time_split[0].to_i
      if time_split[0].to_i  == 0 then
        time_split[0] = 12
      end
  
      result = "#{date} #{time_split.join ":"}"
      return result
    end
  end
  
  #History Report - User - Laptop - When - Checked Out Time - Checked In Time
  def history_report(transaction, x)
    @transaction = Transaction.find(transaction)
    laptopID = @transaction.laptops_id
    userID = @transaction.users_id
    outTime = format_timestamp(@transaction.checked_out_time)
    inTime = @transaction.checked_in_time
    
    if inTime == nil then
      inTime = "N/A"
    else
      inTime = format_timestamp(@transaction.checked_in_time)
    end
    
    laptop = LaptopsController.new.find_laptop_by_id(laptopID.to_i)
    user = UsersController.new.find_user_by_id(userID.to_i)
    #laptopName = laptop.item_name
    #laptopCode = laptop.scan_code
    
    report = [laptop, outTime, inTime, user, laptopID, userID]
    return report[x]
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
  end
  
  def laptops
    return "Test"
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)
    respond_to do |format|
      if @transaction.save
        format.html { redirect_to '/check-out', notice: 'Transaction was successfully created.' }
        format.json { render action: 'show', status: :created, location: @transaction }
        check_out()
        UserHistoriesController.new.add_record(@transaction)
        LaptopHistoriesController.new.add_record(@transaction)
      else
        format.html { render action: 'new' }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1
  # PATCH/PUT /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to @transaction, notice: 'Transaction was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_params
      if params[:transaction].present?
        params.require(:transaction).permit(:laptops_id, :users_id, :checked_out, :checked_out_time, :checked_in, :checked_in_time)
      end
    end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<% provide(:title, 'Laptops') %>
<style>
		h1 {
			text-align: center;
			font-family: arial;
			font-size: 20px;
		}
		
		body {
			text-align: center;
		}
		
		form {
			margin: 0 auto;
			font-weight: bold;
			color: black;
			text-align: left;
		}
		
		select {
			width: 150px;
		}
		
		#avail_laptops {
			width: 150px;
		}
		
		#buttons {
			width: 150px;
			display: inline-block;
			padding-left: 1px;
		}
		
		
</style>

<%= form_for(@transaction) do |f| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2>Checkout Failed: <%= pluralize(@transaction.errors.count, "Error") %></h2>

      <ul>
      <% @transaction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field" id="avail_laptops">
    <%= f.label :laptops, "Available Laptops"  %><br>
    <%= f.collection_select(:laptops_id, Laptop.where(:available => true), :id, :item_name) %>
  </div>
  <div class="field">
    <%= f.label :users, "Select User" %><br>
    <%= f.collection_select(:users_id, User.all, :id, :full_name) %>
  </div>
  <div class="actions" id="buttons">
    <a href=<%= root_path %>><button type="button" id="small_button">Home</button></a>
    <%= f.submit "Check Out", :id => "small_button"%>
  </div>
<% end %>

app/views/transactions/edit.html.erb
<h1>Editing transaction</h1>

<%= render 'form' %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<% provide(:title, 'Laptops') %>
<style>		
		h1 {
			text-align: center;
			font-family: arial;
			font-size: 20px;
		}
		
		table {
			border-collapse: collapse;
			width: 0 auto;
			margin: 0 auto;
			empty-cells: show;	
		}
		
		table tr th {
			border-bottom: 2px solid black;
		}
		
		table tr {
			text-align: left;
		}
		
		#navbar {
			width: 0 auto;
			margin: 0 auto;
			float: left;
		}
		
		#spacing {
			padding-right: 40px;
		}
		
		#id {
			text-align: center;
		}
		
		#bottom_border {
			border-top: 2px solid black;
			padding-top: 5px;
		}
</style>
<br />
<header id="logo"></header>
<h1>Checkout Status</h1>


<table>
  <thead>
    <tr>
      <th><div style='width: 150px'>Item</div></th>
      <th><div style='width: 150px'>Checked Out By</div></th>
      <th><div style='width: 150px'>Checked Out At</div></th>
    </tr>
  </thead>

  <tbody>
    <% @transactions.each do |transaction| %>
    		<% if transaction.checked_out == true then %>
    			<tr>
    				<td><%= link_to UsersController.new.find_user_by_id(transaction.users_id.to_i), :controller => "user_histories", :action => "search", :user_id => transaction.users_id %></td>
    				<td><%= LaptopsController.new.find_laptop_by_id(transaction.laptops_id) %></td>
			        <td><%= UsersController.new.find_user_by_id(transaction.users_id.to_i)%></td>
			        <td><%= TransactionsController.new.format_timestamp(transaction.checked_out_time) %></td>
		    	</tr>
    		<% end %>
    <% end %>
    
  </tbody>
  
  <tr>
  	<td id="bottom_border">
  		<div id="navbar">
			<a href="/"><button id="small_button">Home</button></a>
		</div>
  	</td>
  	<td id="bottom_border"></td>
  	<td id="bottom_border"></td>
  </tr>
  
  
</table>

<br>

app/views/transactions/index_all.html.erb
<% provide(:title, 'History') %>
<style>		
		h1 {
			text-align: center;
			font-family: arial;
			font-size: 20px;
		}
		
		table {
			border-collapse: collapse;
			width: 0 auto;
			margin: 0 auto;
			empty-cells: show;	
		}
		
		table tr th {
			border-bottom: 2px solid black;
		}
		
		table tr {
			text-align: left;
		}
		
		td {
			margin: 0 auto;
			padding-right: 5px;
			padding-left: 5px;
		}
		
		#navbar {
			width: 0 auto;
			margin: 0 auto;
			float: left;
		}
		#navbar2 {
			width: 0 auto;
			margin: 0 auto;
			float: right;
		}
		
		#spacing {
			padding-right: 40px;
		}
		
		#id {
			text-align: center;
		}
		
		#bottom_border {
			border-top: 2px solid black;
			padding-top: 5px;
		}
		a { color: #000; }
		a:visited { color: #000; }
		a:hover { color: #fff; background-color:#000; }
</style>
<br />
<header id="logo"></header>
<h1>Checkout History</h1>


<table>
  <thead>
    <tr>
      <th><div style='width: 150px'>Laptop</div></th>
      <th><div style='width: 150px'>Checked Out By</div></th>
      <th><div style='width: 150px'>Checked Out At</div></th>
      <th><div style='width: 150px'>Checked In At</div></th>
    </tr>
  </thead>

  <tbody>
    <% @transactions.each do |transaction| %>
    			<tr>
    				<td>
	    				<%= link_to LaptopsController.new.find_laptop_by_id(transaction.laptops_id),
	    				 :controller => "laptop_histories",
	    				  :action => "search",
	    				   :laptop_id => transaction.laptops_id %>
    				</td>
    				
    				<td>
	    				<%= link_to UsersController.new.find_user_by_id(transaction.users_id.to_i),
	    				 :controller => "user_histories",
	    				  :action => "search",
	    				   :user_id => transaction.users_id %>
    				</td>
    				
			        <td><%= TransactionsController.new.format_timestamp(transaction.checked_out_time) %></td>
			        <td><%= TransactionsController.new.format_timestamp(transaction.checked_in_time) %></td>
		    	</tr>
    <% end %>
    
  </tbody>
  
  <tr>
  	<td id="bottom_border">
  		<div id="navbar">
			<a href=<%= status_path %>><button id="small_button">Back</button></a>
		</div>
  	</td>
  	<td id="bottom_border"></td>
  	<td id="bottom_border"></td>
  	<td id="bottom_border">
  		<div id="navbar2">
			<a href=<%= root_path %>><button id="small_button">Home</button></a>
		</div>
  	</td>
  </tr>
  
  
</table>

<br>

app/views/transactions/new.html.erb
<style>
		h1 {
			text-align: center;
			font-family: arial;
			font-size: 20px;
		}
		
		body {
			
		}
		
		form {
			margin: 0 auto;
			width: 100px;
			padding-right: 50px;
			font-weight: bold;
			color: black;
		}
		
</style>
<br />
<header id="logo"></header>
<h1> Check-Out </h1>

<%= render 'form' %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Laptops:</strong>
  <%= @transaction.laptops_id %>
</p>

<p>
  <strong>Users:</strong>
  <%= @transaction.users_id %>
</p>

<p>
  <strong>Checked out:</strong>
  <%= @transaction.checked_out %>
</p>

<p>
  <strong>Checked out time:</strong>
  <%= @transaction.checked_out_time %>
</p>

<p>
  <strong>Checked in:</strong>
  <%= @transaction.checked_in %>
</p>

<p>
  <strong>Checked in time:</strong>
  <%= @transaction.checked_in_time %>
</p>

<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>