config/routes.rb
LaptopCheckout::Application.routes.draw do
  resources :user_histories, :path => "user/history"
  resources :laptop_histories, :path => "laptop/history"
  resources :transactions
  resources :users, :path => "manage/users"
  resources :laptops, :path => "manage/laptops"
  
  match 'check-in' => 'laptops#scan', via: [:get, :post]
  get 'check-out' => 'transactions#new'
  get 'status' => 'transactions#index'
  get 'manage' => 'index#manage'
  get 'history' => 'transactions#index_all'

  resources :laptops do
    put :scan, :on => :collection
  end
 
  get 'user/view' => 'user_histories#search'
  resources :user_histories do
    collection do
      get 'search'
    end
  end
  
  get 'laptop/view' => 'laptop_histories#search'
  resources :laptop_histories do
    collection do
      get 'search'
    end
  end
  

    

  root 'index#home'

end

app/models/laptop.rb
class Laptop < ActiveRecord::Base
  validates :scan_code,
            :presence => true,
            :uniqueness => { :case_sensitive => true }
  validates :item_name,
            :presence => true,
            :uniqueness => { :case_sensitive => false }
end

app/controllers/laptops_controller.rb
class LaptopsController < ApplicationController
  before_action :set_laptop, only: [:show, :edit, :update, :destroy]
  after_action :scan

  
  # GET /laptops
  # GET /laptops.json
  def index
    @laptops = Laptop.all
  end
  
  def find_laptop_by_id(id)
    laptops = Laptop.all
    laptops.each do |x|
      if x.id == id then
        return x.item_name
      end
    end
  end

  def update_available(scan_code)
    laptops = Laptop.all
    transactions = Transaction.all
    
    laptops.each do |x|
      if x.scan_code == scan_code then
        x.update_attribute(:available, true) 
        transactions.each do |y|
          if y.laptops_id == x.id then
            y.update_attribute(:checked_out, false)
            y.update_attribute(:checked_in_time, Time.now)
          end
        end
        
        break
      end
    end
  end

  # GET /laptops/1
  # GET /laptops/1.json
  def show
  end
  
  def scan
        update_available(params[:scan_code])
        puts "Test"
  end
  
  def checkin_edit
  end

  # GET /laptops/new
  def new
    @laptop = Laptop.new
  end

  # GET /laptops/1/edit
  def edit
  end

  # POST /laptops
  # POST /laptops.json
  def create
    @laptop = Laptop.new(laptop_params)

    respond_to do |format|
      if @laptop.save
        format.html { redirect_to laptops_path, notice: 'Laptop was successfully created.' }
        format.json { render action: 'show', status: :created, location: @laptop }
      else
        format.html { render action: 'new' }
        format.json { render json: @laptop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /laptops/1
  # PATCH/PUT /laptops/1.json
  def update
    respond_to do |format|
      if @laptop.update(laptop_params)
        format.html { redirect_to laptops_path, notice: 'Laptop was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @laptop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /laptops/1
  # DELETE /laptops/1.json
  def destroy
    @laptop.destroy
    respond_to do |format|
      format.html { redirect_to laptops_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_laptop
      @laptop = Laptop.find(params[:id])     
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def laptop_params
      params.require(:laptop).permit(:scan_code, :item_name)
    end
end

app/helpers/laptop_helper.rb
module LaptopHelper
end

app/helpers/laptops_helper.rb
module LaptopsHelper
end

app/views/laptops/_checkin.html.erb
<% provide(:title, 'Laptops') %>
<style>
		h1 {
			text-align: center;
			font-family: arial;
			font-size: 20px;
		}
		
		body {
			
		}
		
		form {
			margin: 0 auto;
			width: 100px;
			padding-right: 50px;
			font-weight: bold;
			color: black;
		}
		
</style>
<body>
<%= form_for(@laptop) do |f| %>
  <% if @laptop.errors.any? %>
    <div id="error_explanation">
      <h2>Cannot save laptop: <%= pluralize(@laptop.errors.count, "Error") %></h2>

      <ul>
      <% @laptop.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :item_name %><br>
    <%= f.text_field :item_name, :disabled => true %>
  </div>
  <div class="field">
    <%= f.label :scan_code %><br>
    <%= f.text_field :scan_code, :disabled => true %>
  </div>
  <div class="field">
    <%= f.label :available %><br>
    <%= f.text_field :available, :disabled => true %>
  </div>
  <div class="actions">
    <%= f.submit %>
	<a href=<%= laptops_path %>><button>Return</button></a>
  </div>
<% end %>
</body>

app/views/laptops/_form.html.erb
<% provide(:title, 'Laptops') %>
<style>
		h1 {
			text-align: center;
			font-family: arial;
			font-size: 20px;
		}
		
		body {
			text-align: center;
		}
		
		form {
			margin: 0 auto;
			font-weight: bold;
			color: black;
			text-align: left;
		}
		
		#form_field {
			width: 160px;
		}
		
		#buttons {
			width: 150px;
			display: inline-block;
			padding-left: 6px;
		}
		
</style>
<body>
<%= form_for(@laptop) do |f| %>
  <% if @laptop.errors.any? %>
    <div id="error_explanation">
      <h2>Cannot save laptop: <%= pluralize(@laptop.errors.count, "Error") %></h2>

      <ul>
      <% @laptop.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :item_name, "Item Name" %><br>
    <%= f.text_field :item_name, :id => "form_field" %>
  </div>
  <div class="field">
    <%= f.label :scan_code, "Scan Code" %><br>
    <%= f.text_field :scan_code, :id => "form_field" %>
  </div>
  <div class="actions" id="buttons">
    <a href=<%= laptops_path %>><button type="button" id="small_button">Back</button></a>
    <%= f.submit "Create", :id => "small_button" %>
  </div>
<% end %>
</body>

app/views/laptops/backup_form.html.erb
<% provide(:title, 'Laptops') %>
<style>
		h1 {
			text-align: center;
			font-family: arial;
			font-size: 20px;
		}
		
		body {
			
		}
		
		form {
			margin: 0 auto;
			width: 100px;
			padding-right: 50px;
			font-weight: bold;
			color: black;
		}
		
</style>
<body>
<%= form_for(@laptop) do |f| %>
  <% if @laptop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@laptop.errors.count, "error") %> prohibited this laptop from being saved:</h2>

      <ul>
      <% @laptop.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :item_name %><br>
    <%= f.text_field :item_name %>
  </div>
  <div class="field">
    <%= f.label :scan_code %><br>
    <%= f.text_field :scan_code %>
  </div>
  <div class="actions">
    <%= f.submit %>
	<a href="/laptops"><button>Return</button></a>
  </div>
<% end %>
</body>

app/views/laptops/edit.html.erb
<style>
		h1 {
			text-align: center;
			font-family: arial;
			font-size: 20px;
		}
		
		body {
			
		}
		
		form {
			margin: 0 auto;
			width: 100px;
			padding-right: 50px;
			font-weight: bold;
			color: black;
		}
		
</style>
<br />
<header id="logo"></header>
<h1> Editing Laptop </h1>

<%= render 'form' %>

app/views/laptops/index.html.erb
<% provide(:title, 'Laptops') %>
<style>		
		h1 {
			text-align: center;
			font-family: arial;
			font-size: 20px;
		}
		
		table {
			border-collapse: collapse;
			width: 0 auto;
			margin: 0 auto;
			empty-cells: show;
			
		}
		
		table tr th {
			border-bottom: 2px solid black;
		}
		
		td, th {
			margin: 0 auto;
			padding-left:2px;
			padding-right:2px;
		}
		
		table tr {
			text-align: left;
		}
		
		#navbar {
			width: 0 auto;
			margin: 0 auto;
			float: left;
		}
		
		#spacing {
			padding-right: 40px;
		}
		
		#id {
			text-align: center;
		}
		
		#bottom_border {
			border-top: 2px solid black;
			padding-top: 5px;
		}
		a { color: #000; }
		a:visited { color: #000; }
		a:hover { color: #fff; background-color:#000; }
</style>
<br />
<header id="logo"></header>
<h1>Laptops</h1>

<table>
  <thead>
    <tr>
      <th id="id">#</th>
      <th>Item</th>
      <th>Scan Code</th>
      <th></th>
      <th></th>
    </tr>
  </thead>


  <tbody>
    <% @laptops.each do |laptop| %>
      <tr>
      	<td id="id"><%= laptop.id %></td>
    	<td id="spacing">
	    	<%= link_to "#{laptop.item_name}",
	    		:controller => "laptop_histories",
	    		:action => "search",
	    		:laptop_id => laptop.id %>
    	</td>
        <td id="spacing"> <%= laptop.scan_code%> </td>
        <td><button id="table_button"><%= link_to 'Edit', edit_laptop_path(laptop) %></button></td>
        <td><button id="table_button"><%= link_to 'Delete', laptop, method: :delete, data: { confirm: 'Are you sure?' } %></button></td>
      </tr>
    <% end %>
  </tbody>
  
  <tr>
  	<td id="bottom_border">
  		<div id="navbar">
			<a href="/manage"><button id="small_button">Back</button></a>
		</div>
  	</td>
  	<td id="bottom_border">
  		<div id="navbar">
			<a href=<%= root_path %>><button id="small_button">Home</button></a>
		</div>
  	</td>
  	<td id="bottom_border"></td>
  	<td id="bottom_border"></td>
  	<td id="bottom_border"><button id="table_button"><%= link_to 'New', new_laptop_path %></button></td>
  </tr>
</table>

<br>

app/views/laptops/new.html.erb
<style>
		h1 {
			text-align: center;
			font-family: arial;
			font-size: 20px;
		}
		
		body {
			
		}
		
		form {
			margin: 0 auto;
			width: 100px;
			padding-right: 50px;
			font-weight: bold;
			color: black;
		}
		
</style>
<br />
<header id="logo"></header>
<h1> New Laptop </h1>

<%= render 'form' %>

app/views/laptops/scan.html.erb
<% provide(:title, 'Laptops') %>
<style>
		h1 {
			text-align: center;
			font-family: arial;
			font-size: 20px;
		}
		
		body {
			
		}
		
		form {
			margin: 0 auto;
			width: 0 auto;
			text-align: center;
			font-weight: bold;
			color: black;
		}
		div {
			margin: 0 auto;
			width: 0 auto;
			text-align: center;
			padding-right: 155px;
			padding-top: 5px;
		}
		
</style>
<br />
<header id="logo"></header>
<h1>Check-In Laptop</h1>

<script>
	function resetForm(form){
    	form.reset();
	}
	function clearField(field){
		field.value = '';
		return true;
	}
	function clearText(field){
		if(field.defaultValue == field.value){
		field.value = “”;
		} 
		else if(field.value == “”){
			field.value = field.defaultValue;
		}
	}
	
</script>

<body>
	<form action="check-in" method="post">
		<%= token_tag %>
	    <%= text_field_tag :scan_code, params[:scan_code], :placeholder => "Scan Code", :id => "scan_tag", :autofocus => true %>  
	    
	    <%= button_tag(:id => "small_button", :type => 'submit', :name => nil) do
  			content_tag(:strong, 'Check-In') end %>		
	</form> 
	  	<div class="actions">
			<a href="/"><button id="small_button">Home</button></a>
  		</div>
</body>

app/views/laptops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Scan code:</strong>
  <%= @laptop.scan_code %>
</p>

<p>
  <strong>Item name:</strong>
  <%= @laptop.item_name %>
</p>

<p>
  <strong>Available?:</strong>
  <%= @laptop.available %>
</p>

<%= link_to 'Edit', edit_laptop_path(@laptop) %> |
<%= link_to 'Back', laptops_path %>